models/envVariables.py
import os
from dotenv import load_dotenv

load_dotenv()

serviceUrl = os.getenv('serviceUrl')
projectUrl = os.getenv('projectUrl')
host = os.getenv('host')
port = os.getenv('port')

controllers/__init__.py
import os
from flask import Blueprint, current_app, make_response,request

from controllers.news_controller import home as news_home
from controllers.news_controller import newsPost as news_post
from controllers.subjects_controller import subjectsList as subjects_list
from controllers.subjects_controller import newsBySubjects as news_by_subjects
from controllers.subjects_controller import getSubjects

from models.envVariables import serviceUrl,projectUrl


template_dir = os.path.abspath('sitedenoticiasuser/templates/')

news_bp = Blueprint("news",__name__,template_folder=template_dir)
subjects_bp = Blueprint("subjects",__name__,template_folder=template_dir)

def envVariablesDict():
    res = getSubjects(1,3)
    return dict(subjectsListForMenu=res,serviceUrl=serviceUrl,projectUrl=projectUrl)


@news_bp.context_processor
def inject_news_subjects():
    return envVariablesDict()


@subjects_bp.context_processor
def inject_news_subjects():
    return envVariablesDict()



@news_bp.route("/")
def home():
    req = request.args
    pageNumber = req.get("pageNumber",1)
    limit = req.get("limit",4)

    return news_home(limit,pageNumber)

@news_bp.route("/newsPost/<int:postId>")
def newsPost(postId):
    return news_post(postId)


@subjects_bp.route("/homesubject/<string:subject>")
def subjectsList(subject):
    req = request.args
    pageNumber = req.get("pageNumber",1)
    limit = req.get("limit",4)
    return news_by_subjects(pageNumber,limit,subject)

@subjects_bp.route("/homesubject")
def homeSubject():
    req = request.args
    pageNumber = req.get("pageNumber",1)
    limit = req.get("limit",4)
    return subjects_list(pageNumber,limit)

controllers/news_controller.py
from flask import jsonify, render_template
import requests
from controllers.subjects_controller import getAllSubjects
from models.envVariables import serviceUrl

def getNews(startNumber,limit):
    try:
        response = requests.get(f'{serviceUrl}/getallnews?startNumber={startNumber}&quantity={limit}')
        return response.json()
    except:
        return {}

def getNewsPost(id):
    try:
        response = requests.get(f'{serviceUrl}/getnews?id={id}')
        return response.json()
    except:
        return {}

#retorno dos templates

def home(limit,pageNumber):
    startNumber = (int(limit)*int(pageNumber))-(int(limit)-1)
    noticias=getNews(startNumber,limit)
    assuntos = getAllSubjects()
    return render_template("home.html",newsList=noticias,subjects=assuntos,pageNumber=pageNumber,quantity=limit)


def newsPost(id):
    noticia = getNewsPost(id)
    assuntos = getAllSubjects()
    return render_template("newsPost.html",newsDetails=noticia,subjects=assuntos)

controllers/subjects_controller.py
from flask import  jsonify, render_template
import requests
from models.envVariables import serviceUrl

def getSubjects(startNumber,limit):
    try:
        response = requests.get(f"{serviceUrl}/getsubjects?startNumber={startNumber}&quantity={limit}")
        return response.json()
    except:
        return []

def getAllSubjects():
    try:
        response = requests.get(f"{serviceUrl}/getallsubjects")
        return response.json()
    except:
        return []

def getSubjects(startNumber,limit):
    try:
        response = requests.get(f"{serviceUrl}/getsubjects?startNumber={startNumber}&quantity={limit}")
        return response.json()
    except:
        return []

def getSubjectById(id):
    try:
        response = requests.get(f"{serviceUrl}/getnewsbyid?id={id}")
        return response.json()
    except:
        return {}

def getNewsSubjects(startNumber,limit,subject):
    try:
        response = requests.get(f'{serviceUrl}/getallnewsbysubject?startNumber={startNumber}&quantity={limit}&assunto={subject}')
        return response.json()
    except:
        return []

def subjectsList(pageNumber,limit):
    startNumber = (int(limit)*int(pageNumber))-(int(limit)-1)
    assuntos = getSubjects(startNumber,limit)
    return render_template("homeSubjects.html",subjects=assuntos,pageNumber=pageNumber,quantity=limit)

def newsBySubjects(startNumber,limit,subject):
    assunto = getSubjectById(subject)
    noticias = getNewsSubjects(startNumber,limit,subject)
    return render_template("newsBySubjects.html",newsList=noticias,subject=assunto)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% block head %} {% endblock %}
  </head>
  <body>
    <div class="content">
      <div class="header">
        <!--ignorar-->
        <h1
          class="logo"
          onclick="window.location.href='{{ url_for( 'news.home' ) }}';"
        >
          CarolNews
        </h1>
        <div class="menu">
          <a href="{{url_for('subjects.homeSubject')}}">Assuntos</a>
          {% for key,value in subjectsListForMenu.items() %}
          <a
            class="subject"
            href="{{url_for('subjects.subjectsList',subject=key)}}"
            >{{value}}</a
          >
          {% endfor %}
        </div>
      </div>
      <hr class="headerHr" />
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

<style>
  body {
    width: auto;
    margin: auto;
    height: 100%;
    max-width: 1100px;
    font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS",
      sans-serif;
    background-color: #0468aa;
  }

  .content {
    width: 100%;
    height: 100%;
    padding: 2%;
    background-color: white;
  }

  .subject {
    font-size: large;
    color: #0468aa;
  }

  .blueText {
    color: #0468aa;
  }

  .grayText {
    color: dimgrey;
  }

  hr {
    width: 100%;
    background-color: #0468aa;
    border: 1px solid #0468aa;
  }

  button {
    background-color: #0468aa;
    color: white;
    border: 1px solid #ddd;
    padding: 5px;
    padding-left: 8px;
    padding-right: 8px;
    margin-right: 7px;
    margin-top: 7px;
    margin-bottom: 7px;
    border-radius: 4px;
  }

  button:hover {
    background-color: #0e1b8b;
  }

  input {
    margin-left: 10px;
    margin-right: 10px;
    margin-bottom: 10px;
    border: 1px solid #ddd;
    padding: 4px;
    border-radius: 4px;
  }

  a {
    color: #0468aa;
  }

  select {
    padding: 4px;
    margin-left: 10px;
    margin-bottom: 10px;
    margin-right: 10px;
    border: 1px solid #ddd;
    border-radius: 4px;
  }

  .header {
    width: 100%;
    display: inline-flex;
    justify-content: flex-start;
    align-items: center;
  }

  .menu {
    font-size: medium;
    padding-left: 3%;
    font-weight: bold;
  }

  .menu a {
    margin-right: 20px;
  }

  .headerHr {
    width: 100%;
    height: 5%;
    background-color: #0468aa;
    border: 1px solid #0468aa;
  }

  .logo {
    padding-right: 5px;
    user-select: none;
  }

  .modal {
    position: relative;
    width: fit-content;
    height: fit-content;
    padding: 1%;
    margin-bottom: 1%;
    background-color: white;
    text-align: center;
    border: 3px solid #0468aa;
    cursor: pointer;
  }

  .newsContent {
    margin-left: 2%;
  }

  p {
    text-align: justify;
    margin: -22px;
    background-color: white;
    padding: 2%;
  }
</style>

templates/home.html
{% block head %}
<title>Home</title>
{% endblock %} {% extends 'base.html' %} {% block content %}
<h1>Todas noticias</h1>
<label>Quantidade por pagina:</label>
<input
  type="text"
  value="{{quantity}}"
  id="limitPerPage"
  onchange="changeLimit(value)"
/>
<dl>
  {% for news in newsList %}
  <div>
    <hr />
    <dt>
      <b class="subject">[{{subjects.get(news.assunto)}}]</b>
      <a href="{{url_for('news.newsPost',postId=news.id)}}"> {{news.titulo}}</a>
      <div class="newsContent">{{news.resumo}}</div>
    </dt>
    <br />
  </div>
  {% endfor %}

  <button onclick="changePage({{pageNumber}}-1,{{quantity}})"><-</button>
  <label id="pageLabel">{{pageNumber}}</label>
  <button onclick="changePage({{pageNumber}}+1,{{quantity}})">-></button>
</dl>
<script>
  const userBaseUrl = {{projectUrl | tojson}}
    const news = {{newsList | tojson}}
    const currentPage = {{pageNumber | tojson}}

    function changePage(newPage, quantity) {
    	if (newPage <= 0) return;
    	if (news.length < quantity && newPage > currentPage) return;
    	window.location = `${userBaseUrl}?pageNumber=${newPage}&limit=${quantity}`
    }

    function changeLimit(value){
    	window.location = `${userBaseUrl}?pageNumber=${currentPage}&limit=${value}`;
    }
</script>
{% endblock content %}

templates/homeSubject.html
{% block head %}
<title>{{subject}}</title>
{% endblock %} {% extends 'base.html' %} {% block content %}
<h1>{{subject}}</h1>
<dl>
	{% for news in newsList %}
	<dt>
		<a href="{{url_for('news.newsPost',postId=news.id)}}"
			>[{{news.assunto}}] {{news.titulo}}</a
		>
	</dt>
	{% endfor %}
</dl>
{% endblock content %}

templates/homeSubjects.html
{% block head %}
<title>Assuntos</title>
{% endblock %} {% extends 'base.html' %} {% block content %}
<h1>Assuntos</h1>
<label>Quantidade por pagina:</label>
<input
  type="text"
  value="{{quantity}}"
  id="limitPerPage"
  onchange="changeLimit(value)"
/>
<dl>
  {% for key,value in subjects.items() %}
  <a class="subject" href="{{url_for('subjects.subjectsList',subject=key)}}"
    >{{value}}</a
  >
  <br />
  {% endfor %}

  <button onclick="changePage({{pageNumber}}-1,{{quantity}})"><-</button>
  <label id="pageLabel">{{pageNumber}}</label>
  <button onclick="changePage({{pageNumber}}+1,{{quantity}})">-></button>
</dl>
<script>
     const userBaseUrl = {{projectUrl | tojson}}
  const subjectsList = {{subjects | tojson}}
  const currentPage = {{pageNumber | tojson}}

  function changePage(newPage, quantity) {
  	subjectsListLength = Object.keys(subjectsList).length
  	if (newPage <= 0) return;
  	if (subjectsListLength < quantity && newPage > currentPage) return;
  	window.location = `${userBaseUrl}/homesubject?pageNumber=${newPage}&limit=${quantity}`
  }

  function changeLimit(value){
  	window.location = `${userBaseUrl}/homesubject?pageNumber=${currentPage}&limit=${value}`;
  }
</script>
{% endblock content %}

templates/newsBySubjects.html
{% block head %}
<title>{{subject}}</title>
{% endblock %} {% extends 'base.html' %} {% block content %}
<h1>{{subject.subjectName}}</h1>
<dl>
	{% for news in newsList %}
	<div>
		<hr />
		<dt>
			<b class="subject">[{{subject.subjectName}}] </b>
			<a href="{{url_for('news.newsPost',postId=news.id)}}">
				{{news.titulo}}</a
			>
			<div class="newsContent">{{news.resumo}}</div>
		</dt>
		<br />
	</div>
	{% endfor %}
</dl>
{% endblock content %}

templates/newsPost.html
{% block head %}
<title>{{newsDetails.titulo}}</title>
{% endblock %} {% extends 'base.html' %} {% block content %}
<h1 class="blueText">{{newsDetails.titulo}}</h1>
<h3 class="grayText">[{{subjects.get(newsDetails.assunto)}}]</h3>
<p>{{newsDetails.conteudo}}</p>
{% endblock %}